language: java

script: mvn install

before_install:
- ./etc/before.sh

cache:
  directories:
  - .autoconf
  - $HOME/.m2

deploy:
  skip_cleanup: true
  provider: script
  script: mvn deploy
  on:
    branch: master
    
after_deploy:
  - ./etc/after.sh
